dist: trusty
sudo: false
os:
  - osx
  - linux
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - |
    if [ $TRAVIS_OS_NAME = "osx" ]; then
      npm install -g yarn
    fi
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn
script:
  - yarn test