dist: trusty
sudo: false
os:
  - osx
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn
script:
  - yarn test