sudo: false
os:
  - osx
  - linux
node_js: 8
cache:
  yarn: true
  directories:
    - node_modules
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - yarn && yarn compile && yarn test